### ISSUE TITLE
[Feature] Run scrcpy through a button

### ISSUE THREAD

**Issue by SalahAdDin** [y-polek/ADB-Wi-Fi#13]
Hello,

Thanks for this great plugin, it also includes `scrcpy` support; but, it is not intuitive to user it with this plugin, i really couldn't find the way to run `scrcpy` but just with the bash command; hence, i don't understand what this feature does do.

Could you add some documentation about it? or, could you add a button/command to launch `scrcpy` from the tool?

Thanks!

**Comment by y-polek** [comment]
Hello!
There is a small `Share screen with 'scrcpy'` button at the bottom-right corner of the device list item.
Clicking on it should open `scrcpy` window.

<img width="366" alt="Screen Shot 2021-08-05 at 10 47 14" src="https://user-images.githubusercontent.com/6666447/128312590-61e0afb6-9464-4f5f-9bc9-6d4ae722002f.png">

**Comment by SalahAdDin** [comment]
> Hello!
> There is a small `Share screen with 'scrcpy'` button at the bottom-right corner of the device list item.
> Clicking on it should open `scrcpy` window.
> 
> <img alt="Screen Shot 2021-08-05 at 10 47 14" width="366" src="https://user-images.githubusercontent.com/6666447/128312590-61e0afb6-9464-4f5f-9bc9-6d4ae722002f.png">

I think i'm dumb because i didn't understand it as `scrcpy`, maybe the icon is not so intuitive, what's about a device icon?

**Comment by y-polek** [comment]
@SalahAdDin Yeah, the icon is far from perfect. Phone screen icon should be more intuitive.
I'll figure something out for the next release.

**Comment by y-polek** [comment]
I changed the icon to a monitor icon.
I chose a monitor instead of a phone icon because a phone icon of such a small size doesn't look good.
And monitor icon resembles scrcpy official [icon](https://github.com/Genymobile/scrcpy/blob/master/data/icon.png).

<img width="300" alt="Screenshot 2021-11-22 at 10 37 39" src="https://user-images.githubusercontent.com/6666447/142829220-ecffb169-9aa1-4126-8ce7-5a944584163f.png">
