### ISSUE TITLE
Add support of non-default port number (5555)

### ISSUE THREAD

**Issue by y-polek** [y-polek/ADB-Wi-Fi#8]

**Comment by robbelDev** [comment]
Are you working on it? Because this feature is needed for the new wifi debugging of android 11. [https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+](url) 
There you get a custom port to connect to from the android device.
And to be complete able to use this with your plugin, there is a function for this: `adb pair id:port` needed.

**Comment by y-polek** [comment]
Implemented in [v1.2.4](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.2.4)
